-- Migration Script Generated by inspect-schema.ts
-- Generated at: 2025-12-07T17:30:57.323Z

-- Enable UUID extension if needed
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

BEGIN;

-- Add missing column id to moments
ALTER TABLE moments ADD COLUMN IF NOT EXISTS id uuid DEFAULT uuid_generate_v4();
ALTER TABLE moments ALTER COLUMN id DROP DEFAULT;
ALTER TABLE moments ALTER COLUMN id SET NOT NULL;

-- Add missing column user_id to moments
ALTER TABLE moments ADD COLUMN IF NOT EXISTS user_id uuid DEFAULT uuid_generate_v4();
ALTER TABLE moments ALTER COLUMN user_id DROP DEFAULT;
ALTER TABLE moments ALTER COLUMN user_id SET NOT NULL;

-- Add missing column storage_path to moments
ALTER TABLE moments ADD COLUMN IF NOT EXISTS storage_path text DEFAULT '';
ALTER TABLE moments ALTER COLUMN storage_path DROP DEFAULT;
ALTER TABLE moments ALTER COLUMN storage_path SET NOT NULL;

-- Add missing column description to moments
ALTER TABLE moments ADD COLUMN IF NOT EXISTS description text;

-- Add missing column duration_seconds to moments
ALTER TABLE moments ADD COLUMN IF NOT EXISTS duration_seconds integer;

-- Add missing column status to moments
ALTER TABLE moments ADD COLUMN IF NOT EXISTS status text DEFAULT 'pending_review';
ALTER TABLE moments ALTER COLUMN status SET NOT NULL;

-- Add missing column visibility to moments
ALTER TABLE moments ADD COLUMN IF NOT EXISTS visibility text DEFAULT 'public';
ALTER TABLE moments ALTER COLUMN visibility SET NOT NULL;

-- Add missing column created_at to moments
ALTER TABLE moments ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now();
ALTER TABLE moments ALTER COLUMN created_at SET NOT NULL;

-- Add missing column updated_at to moments
ALTER TABLE moments ADD COLUMN IF NOT EXISTS updated_at timestamp DEFAULT now();
ALTER TABLE moments ALTER COLUMN updated_at SET NOT NULL;

-- Add missing column id to moment_reactions
ALTER TABLE moment_reactions ADD COLUMN IF NOT EXISTS id uuid DEFAULT uuid_generate_v4();
ALTER TABLE moment_reactions ALTER COLUMN id DROP DEFAULT;
ALTER TABLE moment_reactions ALTER COLUMN id SET NOT NULL;

-- Add missing column moment_id to moment_reactions
ALTER TABLE moment_reactions ADD COLUMN IF NOT EXISTS moment_id uuid DEFAULT uuid_generate_v4();
ALTER TABLE moment_reactions ALTER COLUMN moment_id DROP DEFAULT;
ALTER TABLE moment_reactions ALTER COLUMN moment_id SET NOT NULL;

-- Add missing column user_id to moment_reactions
ALTER TABLE moment_reactions ADD COLUMN IF NOT EXISTS user_id uuid DEFAULT uuid_generate_v4();
ALTER TABLE moment_reactions ALTER COLUMN user_id DROP DEFAULT;
ALTER TABLE moment_reactions ALTER COLUMN user_id SET NOT NULL;

-- Add missing column reaction to moment_reactions
ALTER TABLE moment_reactions ADD COLUMN IF NOT EXISTS reaction text DEFAULT 'like';
ALTER TABLE moment_reactions ALTER COLUMN reaction SET NOT NULL;

-- Add missing column created_at to moment_reactions
ALTER TABLE moment_reactions ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now();
ALTER TABLE moment_reactions ALTER COLUMN created_at SET NOT NULL;

-- Add missing column id to moment_reports
ALTER TABLE moment_reports ADD COLUMN IF NOT EXISTS id uuid DEFAULT uuid_generate_v4();
ALTER TABLE moment_reports ALTER COLUMN id DROP DEFAULT;
ALTER TABLE moment_reports ALTER COLUMN id SET NOT NULL;

-- Add missing column moment_id to moment_reports
ALTER TABLE moment_reports ADD COLUMN IF NOT EXISTS moment_id uuid DEFAULT uuid_generate_v4();
ALTER TABLE moment_reports ALTER COLUMN moment_id DROP DEFAULT;
ALTER TABLE moment_reports ALTER COLUMN moment_id SET NOT NULL;

-- Add missing column reporter_id to moment_reports
ALTER TABLE moment_reports ADD COLUMN IF NOT EXISTS reporter_id uuid DEFAULT uuid_generate_v4();
ALTER TABLE moment_reports ALTER COLUMN reporter_id DROP DEFAULT;
ALTER TABLE moment_reports ALTER COLUMN reporter_id SET NOT NULL;

-- Add missing column reason to moment_reports
ALTER TABLE moment_reports ADD COLUMN IF NOT EXISTS reason text DEFAULT '';
ALTER TABLE moment_reports ALTER COLUMN reason DROP DEFAULT;
ALTER TABLE moment_reports ALTER COLUMN reason SET NOT NULL;

-- Add missing column reason_text to moment_reports
ALTER TABLE moment_reports ADD COLUMN IF NOT EXISTS reason_text text;

-- Add missing column created_at to moment_reports
ALTER TABLE moment_reports ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now();
ALTER TABLE moment_reports ALTER COLUMN created_at SET NOT NULL;

-- Add missing column id to blocks
ALTER TABLE blocks ADD COLUMN IF NOT EXISTS id uuid DEFAULT uuid_generate_v4();
ALTER TABLE blocks ALTER COLUMN id DROP DEFAULT;
ALTER TABLE blocks ALTER COLUMN id SET NOT NULL;

-- Add missing column blocker_id to blocks
ALTER TABLE blocks ADD COLUMN IF NOT EXISTS blocker_id uuid DEFAULT uuid_generate_v4();
ALTER TABLE blocks ALTER COLUMN blocker_id DROP DEFAULT;
ALTER TABLE blocks ALTER COLUMN blocker_id SET NOT NULL;

-- Add missing column blocked_id to blocks
ALTER TABLE blocks ADD COLUMN IF NOT EXISTS blocked_id uuid DEFAULT uuid_generate_v4();
ALTER TABLE blocks ALTER COLUMN blocked_id DROP DEFAULT;
ALTER TABLE blocks ALTER COLUMN blocked_id SET NOT NULL;

-- Add missing column created_at to blocks
ALTER TABLE blocks ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now();
ALTER TABLE blocks ALTER COLUMN created_at SET NOT NULL;

-- Add missing column id to device_tokens
ALTER TABLE device_tokens ADD COLUMN IF NOT EXISTS id uuid DEFAULT uuid_generate_v4();
ALTER TABLE device_tokens ALTER COLUMN id DROP DEFAULT;
ALTER TABLE device_tokens ALTER COLUMN id SET NOT NULL;

-- Add missing column user_id to device_tokens
ALTER TABLE device_tokens ADD COLUMN IF NOT EXISTS user_id uuid DEFAULT uuid_generate_v4();
ALTER TABLE device_tokens ALTER COLUMN user_id DROP DEFAULT;
ALTER TABLE device_tokens ALTER COLUMN user_id SET NOT NULL;

-- Add missing column platform to device_tokens
ALTER TABLE device_tokens ADD COLUMN IF NOT EXISTS platform text DEFAULT '';
ALTER TABLE device_tokens ALTER COLUMN platform DROP DEFAULT;
ALTER TABLE device_tokens ALTER COLUMN platform SET NOT NULL;

-- Add missing column token to device_tokens
ALTER TABLE device_tokens ADD COLUMN IF NOT EXISTS token text DEFAULT '';
ALTER TABLE device_tokens ALTER COLUMN token DROP DEFAULT;
ALTER TABLE device_tokens ALTER COLUMN token SET NOT NULL;

-- Add missing column is_active to device_tokens
ALTER TABLE device_tokens ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;
ALTER TABLE device_tokens ALTER COLUMN is_active SET NOT NULL;

-- Add missing column created_at to device_tokens
ALTER TABLE device_tokens ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now();
ALTER TABLE device_tokens ALTER COLUMN created_at SET NOT NULL;

-- Add missing column updated_at to device_tokens
ALTER TABLE device_tokens ADD COLUMN IF NOT EXISTS updated_at timestamp DEFAULT now();
ALTER TABLE device_tokens ALTER COLUMN updated_at SET NOT NULL;

COMMIT;