/**
 * Data Validation Utilities
 * 
 * Provides utilities for validating and handling legacy data issues.
 * Helps identify and handle data structure mismatches gracefully.
 */

import { logError } from './errorHandling';

/**
 * Validates that a feed moment row has all required fields
 * Handles legacy data that might be missing fields
 */
export function validateFeedMomentRow(row: any): {
  isValid: boolean;
  errors: string[];
  sanitized: any;
} {
  const errors: string[] = [];
  const sanitized: any = { ...row };

  // Required fields
  if (!row.id) errors.push('Missing id');
  if (!row.storage_path && !row.uri) {
    errors.push('Missing storage_path or uri (legacy field)');
    // Try to use legacy uri field if storage_path is missing
    if (row.uri) {
      sanitized.storage_path = row.uri;
    }
  }
  if (!row.created_at) errors.push('Missing created_at');
  if (!row.user_id) errors.push('Missing user_id');

  // Profile fields (may be null for legacy data)
  if (!row.username) {
    errors.push('Missing username');
    sanitized.username = 'unknown';
  }
  sanitized.display_name = row.display_name ?? null;

  // Reaction fields (may be null)
  sanitized.like_count = typeof row.like_count === 'number' ? row.like_count : 0;
  sanitized.has_liked = row.has_liked ?? false;

  return {
    isValid: errors.length === 0,
    errors,
    sanitized,
  };
}

/**
 * Validates that a profile has all required fields
 */
export function validateProfile(profile: any): {
  isValid: boolean;
  errors: string[];
  sanitized: any;
} {
  const errors: string[] = [];
  const sanitized: any = { ...profile };

  if (!profile.id) errors.push('Missing id');
  if (!profile.username) errors.push('Missing username');
  
  // Optional fields
  sanitized.display_name = profile.display_name ?? null;
  sanitized.bio = profile.bio ?? null;
  sanitized.created_at = profile.created_at ?? new Date().toISOString();
  sanitized.updated_at = profile.updated_at ?? new Date().toISOString();

  return {
    isValid: errors.length === 0,
    errors,
    sanitized,
  };
}

/**
 * Validates that a moment record has all required fields
 * Handles both camelCase (CreateMomentPayload) and snake_case (database records) formats
 */
export function validateMomentRecord(moment: any): {
  isValid: boolean;
  errors: string[];
  sanitized: any;
} {
  const errors: string[] = [];
  const sanitized: any = { ...moment };

  // Handle both camelCase (CreateMomentPayload) and snake_case (database records)
  const userId = moment.userId || moment.user_id;
  const storagePath = moment.storagePath || moment.storage_path;
  const durationSeconds = moment.durationSeconds || moment.duration_seconds;

  // id is optional for CreateMomentPayload (auto-generated by database)
  // Only require it for existing records (database reads)
  const isCreatePayload = !moment.id && (moment.userId || moment.storagePath);
  
  if (!isCreatePayload && !moment.id) {
    errors.push('Missing id');
  }
  
  if (!userId) {
    errors.push('Missing user_id');
  } else {
    sanitized.userId = userId;
    sanitized.user_id = userId; // Support both formats
  }
  
  // Handle legacy uri field vs storage_path
  if (!storagePath && !moment.uri) {
    errors.push('Missing storage_path or uri');
  } else if (storagePath) {
    sanitized.storagePath = storagePath;
    sanitized.storage_path = storagePath; // Support both formats
  } else if (moment.uri) {
    // Legacy data: convert uri to storage_path
    sanitized.storage_path = moment.uri;
    sanitized.storagePath = moment.uri;
    if (__DEV__) {
      console.warn('Legacy moment data detected: using uri field as storage_path');
    }
  }

  // Optional fields - handle both formats
  sanitized.description = moment.description ?? null;
  sanitized.durationSeconds = durationSeconds ?? null;
  sanitized.duration_seconds = durationSeconds ?? null;
  sanitized.status = moment.status ?? 'pending_review';
  sanitized.visibility = moment.visibility ?? 'public';
  sanitized.created_at = moment.created_at ?? new Date().toISOString();
  sanitized.updated_at = moment.updated_at ?? new Date().toISOString();
  
  // Preserve id if present
  if (moment.id) {
    sanitized.id = moment.id;
  }

  return {
    isValid: errors.length === 0,
    errors,
    sanitized,
  };
}

/**
 * Logs data validation errors for debugging
 */
export function logValidationErrors(context: string, errors: string[], data: any): void {
  if (__DEV__) {
    console.error(`[Data Validation] ${context}:`, {
      errors,
      data: JSON.stringify(data, null, 2),
    });
  }
  logError(`Data validation failed in ${context}: ${errors.join(', ')}`);
}

